name: Docker Build and Deploy to ECR

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Build, Push Docker Image to Corp Account
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      AWS_REGION: us-west-2  # Specify your AWS region
      ECR_REGISTRY: "710999489330.dkr.ecr.us-west-2.amazonaws.com/poc"  # ECR registry URL (e.g., 123456789012.dkr.ecr.us-east-1.amazonaws.com)
      ECR_REPOSITORY: "poc"  # ECR repository name
      ECS_CLUSTER: "poc"  # ECS cluster name
      ECS_SERVICE: "poc"  # ECS service name
      IMAGE_TAG: ${{ github.sha }}  # Use the commit SHA as the image tag

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        id: aws-creds
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::710999489330:role/GitHub_OIDC  # Replace with your IAM role ARN
          aws-region: "us-west-2"

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: poc
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker tag $REGISTRY/$REPOSITORY:$IMAGE_TAG $REGISTRY/$REPOSITORY:latest
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:latest


      - name: Initiate ECR Image Scan
        run: |
          MAX_RETRIES=5
          RETRY_DELAY=30  # seconds
          for ((i=1; i<=MAX_RETRIES; i++)); do
            echo "Attempt $i to start image scan..."
            SCAN_RESULT=$(aws ecr start-image-scan --repository-name poc --image-id imageTag=latest 2>&1)
            if echo "$SCAN_RESULT" | grep -q 'LimitExceededException'; then
              echo "Scan quota exceeded. Waiting $RETRY_DELAY seconds before retrying..."
              sleep $RETRY_DELAY
            else
              echo "Scan started successfully."
              break
            fi
            if [[ $i -eq $MAX_RETRIES ]]; then
              echo "Exceeded maximum retries. Exiting."
              exit 1
            fi
          done

      - name: Check ECR Image Scan Status
        id: scan-status
        run: |
          for i in {1..10}; do
            SCAN_STATUS=$(aws ecr describe-image-scan-findings --repository-name poc --image-id imageTag=latest --query 'imageScanStatus.status' --output text)
            echo "Scan status: $SCAN_STATUS"
            if [[ "$SCAN_STATUS" == "COMPLETE" ]]; then
              exit 0
            elif [[ "$SCAN_STATUS" == "FAILED" ]]; then
              echo "Image scan failed."
              exit 1
            else
              echo "Image scan in progress..."
              sleep 10
            fi
          done
          echo "Image scan timed out."
          exit 1

      - name: Get ECR Image Scan Findings
        run: |
          aws ecr describe-image-scan-findings --repository-name poc --image-id imageTag=latest --output json
