name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - test
      - test-2
      - test-3

jobs:
  dev:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/test'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run tests
        run: |
          pytest

  staging:
    runs-on: ubuntu-latest
    needs: dev
    if: github.ref == 'refs/heads/test-2'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Deploy to staging
        run: |
          # Add your deployment script/commands here
          echo "Deploying to staging environment"

  production:
    runs-on: ubuntu-latest
    needs: staging
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Deploy to production
        run: |
          # Add your deployment script/commands here
          echo "Deploying to production environment"
