name: Compass API IACM Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
      - develop   # Trigger on push to the dev branch
      - stage # Trigger on push to the stage branch
  pull_request:
    branches:
      - main
      - develop
      - stage

jobs:
  terraform:
    name: Terraform Init, Plan and Apply
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
            terraform_version: ${{ vars.TERRAFORM_VERSION }}
            cli_config_credentials_token: ${{ secrets.TFC_TOKEN }}
            terraform_wrapper: true

      - name: Set Environment Variables
        run: |
          echo "GitHub ref: ${{ github.ref }}"
          echo "GTH_OIDC_ROLE_PROD=${{ env.GTH_OIDC_ROLE_PROD }}"  # Print the value directly
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "ENVIRONMENT=prod" >> $GITHUB_ENV
            # Set a test value to ensure propagation
            echo "ROLE_TO_ASSUME=arn:aws:iam::710999489330:role/Github_OIDC" >> $GITHUB_ENV
          else
            echo "Unknown branch"
            exit 1
          fi
          
      - name: Print Environment Variables
        run: |
          echo "ENVIRONMENT=$ENVIRONMENT"
          echo "ROLE_TO_ASSUME=$ROLE_TO_ASSUME"
          echo "Checking environment variables from GITHUB_ENV file:"
          cat $GITHUB_ENV     

      - name: Configure AWS Credentials
        id: aws-creds
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}  # Use the dynamically set role
          aws-region: ${{ vars.AWS_REGION }}  # Specify the AWS region

      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      - name: Terraform Plan
        run: |
          cd terraform
          terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/develop'
        run: |
          cd terraform
          terraform apply -auto-approve tfplan
