name: Java CI with Maven

env:
  NAME: 'Snyk Demo'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    env:
        JAVA_VERSION: '21'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Print name
      run: aws s3 sync .  $JAVA_VERSION
      env:
        BUILD: 'We are currently running the Build job'
